version:         '3'
services:
  flask:
    build:
      context:     .
      dockerfile:  Dockerfile-flask
    environment:
      - FLASK_ENV=development
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
  react:
    build:
      context:     .
      dockerfile:  Dockerfile-yarn
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./public:/public
      - ./src:/src
