FROM node:10-alpine as base


FROM base as builder

COPY package.json /package.json
COPY yarn.lock /yarn.lock
RUN yarn install


FROM base

COPY --from=builder /node_modules /node_modules
COPY --from=builder /package.json /package.json

ENTRYPOINT [ "yarn"]
CMD [ "start" ]
