FROM python:3-alpine as base


FROM base as builder

COPY requirements.txt /requirements.txt

RUN pip install -r /requirements.txt


FROM base

COPY --from=builder /usr/local /usr/local

ENTRYPOINT [ "flask"]
CMD [ "run", "--host=0.0.0.0" ]
